### ISSUE TITLE
Exponent after bracket throws error

### ISSUE THREAD

**Issue by leafthelegend** [viktorstrate/algebra-latex#13]
When attempting to parse strings such as `"(x)^2"` or `"(x+1)^2"`, an error is thrown:
![Screen Shot 2020-11-09 at 4 50 00 pm](https://user-images.githubusercontent.com/66891654/98508820-de581a80-22ab-11eb-8587-45c78c9a79f5.png)
This may have something to do with the fact that I am using the package in the browser via Browserify, but I doubt it since everything else works smoothly. As far as I can tell, exponentiation should have the same syntax as multiplication or addition, just with a `^` in place of a `*`.  Since the others work fine (`"(x+1)*2"` etc), hopefully this should be a simple fix.

**Comment by viktorstrate** [comment]
Hi @leafthelegend 

This is a bug, thank you for reporting it.
I'll work on a fix probably later today.

**Comment by viktorstrate** [comment]
This is fixed in `v2.0.2`

**Comment by leafthelegend** [comment]
It seems like I'm still experiencing the bug in `v2.0.2`. For example running the latest version in RunKit:
![Screen Shot 2020-11-10 at 8 55 12 pm](https://user-images.githubusercontent.com/66891654/98667810-ae3b7500-239a-11eb-8f8e-c6e88bf4e5ad.png)

**Comment by viktorstrate** [comment]
Okay, it apparently didn't push the updates correctly in v2.0.2.
I've pushed the update properly in v2.0.3.
